const CANONICAL_ROLES = {
  PLATFORM_ADMIN: 'PLATFORM_ADMIN',
  DISTRICT_ADMIN: 'DISTRICT_ADMIN',
  COLLECTION_CENTRE_MANAGER: 'COLLECTION_CENTRE_MANAGER',
  CENTER_OPERATOR: 'CENTER_OPERATOR',
  QUALITY_INSPECTOR: 'QUALITY_INSPECTOR',
  FARMER: 'FARMER',
  BUYER: 'BUYER',
  LOGISTICS_COORDINATOR: 'LOGISTICS_COORDINATOR'
};

const ROLES = {
  // Canonical roles
  PLATFORM_ADMIN: 'PLATFORM_ADMIN',
  DISTRICT_ADMIN: 'DISTRICT_ADMIN',
  COLLECTION_CENTRE_MANAGER: 'COLLECTION_CENTRE_MANAGER',
  CENTER_OPERATOR: 'CENTER_OPERATOR',
  QUALITY_INSPECTOR: 'QUALITY_INSPECTOR',
  FARMER: 'FARMER',
  BUYER: 'BUYER',
  LOGISTICS_COORDINATOR: 'LOGISTICS_COORDINATOR',

  // Legacy aliases mapped
  SUPER_ADMIN: 'PLATFORM_ADMIN',
  DISTRICT_OFFICER: 'DISTRICT_ADMIN',
  CENTRE_MANAGER: 'COLLECTION_CENTRE_MANAGER',
  CENTER_MANAGER: 'COLLECTION_CENTRE_MANAGER',
  PROCUREMENT_OFFICER: 'CENTER_OPERATOR'
};

const ALL_ROLES = [
  'PLATFORM_ADMIN',
  'DISTRICT_ADMIN',
  'COLLECTION_CENTRE_MANAGER',
  'CENTER_OPERATOR',
  'QUALITY_INSPECTOR',
  'FARMER',
  'BUYER',
  'LOGISTICS_COORDINATOR',
  // Backward compatibility strings in DB
  'SUPER_ADMIN',
  'DISTRICT_OFFICER',
  'CENTRE_MANAGER',
  'CENTER_MANAGER',
  'PROCUREMENT_OFFICER'
];

/**
 * Normalizes any legacy or alias role string to its canonical equivalent.
 */
const normalizeRole = (role) => {
  if (!role) return null;
  const upper = String(role).toUpperCase();
  if (upper === 'SUPER_ADMIN' || upper === 'PLATFORM_ADMIN') {
    return 'PLATFORM_ADMIN';
  }
  if (upper === 'DISTRICT_ADMIN' || upper === 'DISTRICT_OFFICER') {
    return 'DISTRICT_ADMIN';
  }
  if (upper === 'CENTRE_MANAGER' || upper === 'CENTER_MANAGER' || upper === 'COLLECTION_CENTRE_MANAGER') {
    return 'COLLECTION_CENTRE_MANAGER';
  }
  if (upper === 'CENTER_OPERATOR' || upper === 'PROCUREMENT_OFFICER') {
    return 'CENTER_OPERATOR';
  }
  if (upper === 'QUALITY_INSPECTOR') {
    return 'QUALITY_INSPECTOR';
  }
  if (upper === 'FARMER') {
    return 'FARMER';
  }
  if (upper === 'BUYER') {
    return 'BUYER';
  }
  if (upper === 'LOGISTICS_COORDINATOR') {
    return 'LOGISTICS_COORDINATOR';
  }
  return upper;
};

module.exports = {
  CANONICAL_ROLES,
  ROLES,
  ALL_ROLES,
  normalizeRole
};
