const USER_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  SUSPENDED: 'SUSPENDED',
  ACTIVE: 'APPROVED',
  INACTIVE: 'SUSPENDED'
};

const CENTRE_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  MAINTENANCE: 'MAINTENANCE'
};

const BOOKING_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED',
  EXPIRED: 'EXPIRED',
  RESCHEDULED: 'RESCHEDULED'
};

const TOKEN_STATUS = {
  WAITING: 'WAITING',
  CALLED: 'CALLED',
  ARRIVED: 'ARRIVED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  ABSENT: 'ABSENT',
  CANCELLED: 'CANCELLED',
  RESCHEDULED: 'RESCHEDULED'
};

const PROCUREMENT_STATUS = {
  NOT_STARTED: 'NOT_STARTED',
  ARRIVED: 'ARRIVED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};

const PAYMENT_STATUS = {
  NOT_STARTED: 'NOT_STARTED',
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  PAID: 'PAID',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED'
};

const COUNTER_STATUS = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
  MAINTENANCE: 'MAINTENANCE'
};

const ASSIGNMENT_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE'
};

// AgriTrade Extended Status Enums
const PRODUCE_LOT_STATUS = {
  CREATED: 'CREATED',
  SCHEDULED: 'SCHEDULED',
  RECEIVED: 'RECEIVED',
  UNDER_INSPECTION: 'UNDER_INSPECTION',
  ACCEPTED: 'ACCEPTED',
  PARTIALLY_ACCEPTED: 'PARTIALLY_ACCEPTED',
  REJECTED: 'REJECTED',
  STORED: 'STORED',
  ALLOCATED: 'ALLOCATED',
  DISPATCHED: 'DISPATCHED',
  DELIVERED: 'DELIVERED',
  SETTLED: 'SETTLED',
  CANCELLED: 'CANCELLED'
};

const QUALITY_INSPECTION_STATUS = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  RE_INSPECTED: 'RE_INSPECTED'
};

const QUALITY_GRADE = {
  GRADE_A: 'GRADE_A',
  GRADE_B: 'GRADE_B',
  GRADE_C: 'GRADE_C',
  REJECTED: 'REJECTED'
};

const INVENTORY_MOVEMENT_TYPE = {
  RECEIPT: 'RECEIPT',
  TRANSFER: 'TRANSFER',
  RESERVATION: 'RESERVATION',
  ALLOCATION: 'ALLOCATION',
  DISPATCH: 'DISPATCH',
  ADJUSTMENT: 'ADJUSTMENT'
};

const SETTLEMENT_STATUS = {
  DRAFT: 'DRAFT',
  CALCULATED: 'CALCULATED',
  APPROVED: 'APPROVED',
  SETTLED: 'SETTLED',
  DISPUTED: 'DISPUTED'
};

const DISPUTE_STATUS = {
  OPEN: 'OPEN',
  UNDER_REVIEW: 'UNDER_REVIEW',
  RESOLVED: 'RESOLVED',
  REJECTED: 'REJECTED',
  CLOSED: 'CLOSED'
};

// Phase 4 - B2B Buyer, PO, Logistics & Delivery Enums
const BUYER_VERIFICATION_STATUS = {
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED',
  SUSPENDED: 'SUSPENDED',
  REJECTED: 'REJECTED'
};

const PURCHASE_ORDER_STATUS = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  PARTIALLY_ALLOCATED: 'PARTIALLY_ALLOCATED',
  FULLY_ALLOCATED: 'FULLY_ALLOCATED',
  READY_FOR_DISPATCH: 'READY_FOR_DISPATCH',
  PARTIALLY_DISPATCHED: 'PARTIALLY_DISPATCHED',
  DISPATCHED: 'DISPATCHED',
  PARTIALLY_DELIVERED: 'PARTIALLY_DELIVERED',
  DELIVERED: 'DELIVERED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};

const LOT_ALLOCATION_STATUS = {
  ALLOCATED: 'ALLOCATED',
  DISPATCHED: 'DISPATCHED',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED'
};

const SHIPMENT_STATUS = {
  PLANNED: 'PLANNED',
  READY_FOR_DISPATCH: 'READY_FOR_DISPATCH',
  DISPATCHED: 'DISPATCHED',
  IN_TRANSIT: 'IN_TRANSIT',
  ARRIVED: 'ARRIVED',
  DELIVERED: 'DELIVERED',
  DELAYED: 'DELAYED',
  CANCELLED: 'CANCELLED'
};

const VEHICLE_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  MAINTENANCE: 'MAINTENANCE'
};

const DELIVERY_CONDITION = {
  EXCELLENT: 'EXCELLENT',
  GOOD: 'GOOD',
  DAMAGED_PARTIAL: 'DAMAGED_PARTIAL',
  REJECTED: 'REJECTED'
};

module.exports = {
  USER_STATUS,
  CENTRE_STATUS,
  BOOKING_STATUS,
  TOKEN_STATUS,
  PROCUREMENT_STATUS,
  PAYMENT_STATUS,
  COUNTER_STATUS,
  ASSIGNMENT_STATUS,
  PRODUCE_LOT_STATUS,
  QUALITY_INSPECTION_STATUS,
  QUALITY_GRADE,
  INVENTORY_MOVEMENT_TYPE,
  SETTLEMENT_STATUS,
  DISPUTE_STATUS,
  BUYER_VERIFICATION_STATUS,
  PURCHASE_ORDER_STATUS,
  LOT_ALLOCATION_STATUS,
  SHIPMENT_STATUS,
  VEHICLE_STATUS,
  DELIVERY_CONDITION
};
